# Generated by Django 4.2.1 on 2023-06-15 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20191127_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcontacts',
            name='phone_number',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Phone Number must be of 10 digits', regex='^[0-9]{10}$')]),
        ),
    ]
